// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StockPicksApp.Migrations
{
    [DbContext(typeof(StockPicksDbContext))]
    [Migration("20260424131859_reasonDate")]
    partial class reasonDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PickReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PickReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Microsoft is tied well into enterprises",
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Coupang is the amazon of South Korea",
                            StockId = 3
                        });
                });

            modelBuilder.Entity("StockPickEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("IndexAnnualPercentGain")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("IndexBuyPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("IndexCurrentPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IndexTicker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("IndexTotalPercentGain")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("StockAnnualPercentGain")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StockBuyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("StockBuyPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StockCurrentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("StockCurrentPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("StockTicker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("StockTotalPercentGain")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("StockPicks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IndexBuyPrice = 1000.05m,
                            IndexCurrentPrice = 1005.06m,
                            IndexTicker = "VOO",
                            StockBuyDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockBuyPrice = 400.03m,
                            StockCurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockCurrentPrice = 410.10m,
                            StockTicker = "MSFT"
                        },
                        new
                        {
                            Id = 2,
                            IndexBuyPrice = 1000.05m,
                            IndexCurrentPrice = 1005.06m,
                            IndexTicker = "VOO",
                            StockBuyDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockBuyPrice = 250.03m,
                            StockCurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockCurrentPrice = 251.10m,
                            StockTicker = "AAPL"
                        },
                        new
                        {
                            Id = 3,
                            IndexBuyPrice = 1000.05m,
                            IndexCurrentPrice = 1005.06m,
                            IndexTicker = "VOO",
                            StockBuyDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockBuyPrice = 19m,
                            StockCurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockCurrentPrice = 18.5m,
                            StockTicker = "CPNG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
